spring:
  config:
    import: classpath:environment.properties
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: passwrod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080

jwt:
  signerKey: "KOX/fR5t6kwik5fNnaoNCEe9tJFxcIqAHxUP82D1Pzy/YflIqgBnN26FkUd9kbPz"
  valid-duration: 3600
  refreshable-duration: 36000
